apiVersion: v2
name: dbgate
description: DbGate database manager for Kubernetes and Rancher
type: application
version: 0.1.2
appVersion: "v7.2.6"
keywords:
  - database
  - dbgate
  - admin
maintainers:
  - name: local
