apiVersion: v2
name: dbgate
description: DbGate database manager for Kubernetes and Rancher
type: application
version: 0.1.1
appVersion: "6.5.4"
keywords:
  - database
  - dbgate
  - admin
maintainers:
  - name: local
