{{- include "dbgate.validateRbac" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dbgate.fullname" . }}
  labels:
    {{- include "dbgate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if eq .Values.rbac.engine "sqlite" }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      {{- include "dbgate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dbgate.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: dbgate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "dbgate.authSecretName" . }}
          env:
            - name: AUTH_PROVIDER
              value: {{ .Values.auth.provider | quote }}
            - name: RBAC_STORAGE_ENGINE
              value: {{ .Values.rbac.engine | quote }}
            {{- with .Values.web.root }}
            - name: WEB_ROOT
              value: {{ . | quote }}
            {{- end }}
            {{- if ne .Values.rbac.engine "env" }}
            {{- if .Values.rbac.bootstrap.login }}
            - name: RBAC_BOOTSTRAP_PROVIDER
              value: {{ default .Values.auth.provider .Values.rbac.bootstrap.provider | quote }}
            - name: RBAC_BOOTSTRAP_LOGIN
              value: {{ .Values.rbac.bootstrap.login | quote }}
            {{- end }}
            {{- if .Values.rbac.existingSecret }}
            - name: RBAC_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rbac.existingSecret | quote }}
                  key: RBAC_TOKEN_SECRET
            {{- end }}
            {{- if eq .Values.rbac.engine "sqlite" }}
            - name: RBAC_STORAGE_FILE
              value: {{ .Values.rbac.sqlite.file | quote }}
            {{- else }}
            - name: RBAC_STORAGE_SERVER
              value: {{ .Values.rbac.database.server | quote }}
            - name: RBAC_STORAGE_PORT
              value: {{ default (ternary 5432 3306 (eq .Values.rbac.engine "postgres")) .Values.rbac.database.port | quote }}
            - name: RBAC_STORAGE_DATABASE
              value: {{ .Values.rbac.database.name | quote }}
            - name: RBAC_STORAGE_USER
              value: {{ .Values.rbac.database.user | quote }}
            - name: RBAC_STORAGE_SSL
              value: {{ .Values.rbac.database.ssl | quote }}
            - name: RBAC_STORAGE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rbac.existingSecret | quote }}
                  key: RBAC_STORAGE_PASSWORD
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /root/.dbgate
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "dbgate.fullname" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
